### PR TITLE
switch to cron 3x daily at 6, 14, 22h

### PR DESCRIPTION
**Pull request by tetmin**

### CODE REVIEW

**Review by MarkCatherall — APPROVED** [review]
LGTM. What's the logic of doing it at those times? Should we be doing the middle one early enough for people to see it at lunchtime?

**Review by mgfcatherall — APPROVED** [review]
LGTM.

Last review/approval was from the wrong account, oops.

**Comment by tetmin** [comment]
> LGTM. What's the logic of doing it at those times? Should we be doing the middle one early enough for people to see it at lunchtime?

I was thinking it gets a good spread through both UK & SF timezones since it's 11pm, 7am & 3pm SF time. It also means when the server is redeployed we don't have to wait an extra 8 hours & articles still get published at fixed intervals.

**Comment by tetmin** [comment]
Also - I limited it to 3 articles per day since that's the limit of my free Respell.ai account of $5 credits per month.

**Pull request merged**
